# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Colors
if-shell -b 'infocmp tmux-256color >/dev/null 2>&1' \
        'set -g default-terminal "tmux-256color"' \
        'set -g default-terminal "screen-256color"'

# TrueColor and Italics
set -ga terminal-overrides ',*:Tc'
set -ga terminal-overrides ',*:Sitm=\E[3m'

set -g mouse on
set -g focus-events on

# Window/pane numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Vi copy mode
set-window-option -g mode-keys vi

# Session persistence
set -g @continuum-restore 'on'

set-option -g default-shell $SHELL
if-shell 'command -v reattach-to-user-namespace >/dev/null 2>&1' \
  'set-option -g default-command "reattach-to-user-namespace -l $SHELL"'

# Same pane split bindings
## vertical
bind '|' split-window -c "#{pane_current_path}"
## horizontal
bind '-' split-window -h -c "#{pane_current_path}"
#bind 'c'  command-prompt -I "$PWD" -p "New session dir:" "attach -c %1"
# bind c new-window -c "#{pane_current_path}"

#run-shell '~/.tmux/plugins/tmux-sensible/sensible.tmux'
## Requires tmux-cpu and tmux-net-speed
source-file ~/.tmux/conf.d/clipboard.conf
source-file ~/.tmux/conf.d/scrollback.conf
source-file ~/.tmux/conf.d/status.conf
# This needs to stay at bottom
run '~/.tmux/plugins/tpm/tpm'
